[tool.poetry]
name = "simple-neural-network"
version = "1.0.0"
description = "Introduces a small-scale simple neural network."
authors = ["Elmo Moilanen"]
license = "CC0-1.0"
readme = "README.md"
keywords = ["statistics", "neural network", "supervised learning", "evolutionary algorithms"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23"
matplotlib = "^3.6"
h5py = "^3.6"

[tool.poetry.group.dev.dependencies]
black = "^22.8"
pytest = "^7.1"
flake8 = "^5.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^5.0"
sphinx-rtd-theme = "1.0.0"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | docs
)/
'''

[tool.pytest.ini_options]
addopts = "--doctest-modules --disable-warnings"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
